# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            HUGO PEREIRA
tagline:          'A personal presentation'
description:      'FULL STACK SENIOR SOFTWARE ENGINEER ARCHITECT'
url:              https://github.com/hugorper.github.io
baseurl:          /

author:
  name:           'Hugo Pereira'
  url:            https://twitter.com/hugorper

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/hugorper.github.io

# Gems
plugins:          [jekyll-paginate]
